/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines LaunchDarkly SDK Log Codes
 */
export interface LogCodes {
  [k: string]: System;
}
export interface System {
  specifier: number;
  description: string;
  classes: {
    [k: string]: Class;
  };
}
export interface Class {
  specifier: number;
  description: string;
  codes: {
    [k: string]: Code;
  };
  additionalProperties?: never;
  [k: string]: unknown;
}
export interface Code {
  specifier: number;
  description: string;
  message: Message;
}
export interface Message {
  parameterized: string;
  parameters?: {
    [k: string]: string;
  };
}
